Traceback (most recent call last):
  File "/Users/colinbaker/anaconda3/envs/scootr/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/colinbaker/anaconda3/envs/scootr/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/colinbaker/anaconda3/envs/scootr/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/colinbaker/anaconda3/envs/scootr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/colinbaker/anaconda3/envs/scootr/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/colinbaker/anaconda3/envs/scootr/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/colinbaker/anaconda3/envs/scootr/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
aligned_y_unsup = scootr_sink.get_barycentre(X, pi_samp_unsup)
aligned_y_medsup = scootr_sink.get_barycentre(X, pi_samp_medsup)
aligned_y_fullsup = scootr_sink.get_barycentre(X, pi_samp_fullsup)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[26], line 1[0m
[0;32m----> 1[0m aligned_y_unsup [38;5;241m=[39m scootr_sink[38;5;241m.[39mget_barycentre(X, [43mpi_samp_unsup[49m)
[1;32m      2[0m aligned_y_medsup [38;5;241m=[39m scootr_sink[38;5;241m.[39mget_barycentre(X, pi_samp_medsup)
[1;32m      3[0m aligned_y_fullsup [38;5;241m=[39m scootr_sink[38;5;241m.[39mget_barycentre(X, pi_samp_fullsup)

[0;31mNameError[0m: name 'pi_samp_unsup' is not defined

